models/User.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "user".
 *
 * @property int $id
 * @property string $first_name
 * @property string $last_name
 * @property string $email
 * @property int $personal_code
 * @property int $phone
 * @property bool|null $active
 * @property bool|null $dead
 * @property string|null $lang
 */
class User extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['first_name', 'last_name', 'email', 'personal_code', 'phone'], 'required'],
            [['first_name', 'last_name', 'email', 'lang'], 'string'],
            [['personal_code', 'phone'], 'default', 'value' => null],
            [['personal_code', 'phone'], 'integer'],
            [['personal_code'], 'checkPersonalCode'],
            [['active', 'dead'], 'boolean'],
            [['personal_code'], 'unique', 'targetClass' => '\app\models\User', 'message' => 'Personal Code already taken.'],
            [['email'], 'unique', 'targetClass' => '\app\models\User', 'message' => 'Email address already taken.'],
        ];
    }

    /**
     * Get user's full name.
     *
     * @return string
     */
    public function getName()
    {
        return "{$this->first_name} {$this->last_name}";
    }

    /**
     * Get person birth century.
     *
     * @return int Birth century
     */
    protected function getBirthCentury() : int
    {
        $genderNo = substr($this->personal_code, 0, 1);

        return 1700 + ceil($genderNo / 2) * 100;
    }

    /**
     * Get user's birthday.
     *
     * @return \Datetime
     */
    public function getBirthDate() : \Datetime
    {
        $year = $this->getBirthCentury() + substr($this->personal_code, 1, 2);
        $month = substr($this->personal_code, 3, 2);
        $day = substr($this->personal_code, 5, 2);

        $dob = "{$year}-{$month}-{$day}";

        return new \Datetime($dob);
    }

    /**
     * Get user's age.
     *
     * @param \Datetime $now
     *
     * @return int
     */
    public function getAge(\Datetime $now = null) : int
    {
        if (is_null($now)) {
            $now = new \Datetime();
        }

        return $now->diff($this->getBirthDate())->y;
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'first_name' => 'First Name',
            'last_name' => 'Last Name',
            'name' => Yii::t('app', 'Name'),
            'age' => Yii::t('app', 'Age'),
            'birthDate' => Yii::t('app', 'Date Of Birth'),
            'email' => 'Email Address',
            'personal_code' => 'Personal Code',
            'phone' => 'Phone Number',
            'active' => 'Is Active',
            'dead' => 'Is Dead',
            'lang' => 'Language',
        ];
    }

    /**
     * Loans this user tool.
     *
     * @return \yii\db\ActiveQuery
     */
    public function getLoans()
    {
        return $this->hasMany(Loan::className(), [
            'user_id' => 'id',
        ]);
    }

    /**
     * Validate personal code input.
     */
    public function checkPersonalCode()
    {
        if (! $this->hasErrors() && ! $this->isValidPersonalCode($this->personal_code)) {
            $this->addError('personal_code', 'Invalid personal code.');
        }
    }

    /**
     * Validate personal code.
     *
     * @param string|null $personal_code
     *
     * @return boolean
     */
    protected function isValidPersonalCode($personal_code = null)
    {
        $personal_code = is_null($personal_code) ? $this->personal_code : $personal_code;

        return preg_match('/^[1-6][0-9]{2}[0-1][0-9][0-9]{2}[0-9]{4}$/', $personal_code);
    }
}

controllers/UserController.php
<?php

namespace app\controllers;

use app\models\User;
use app\models\UserSearch;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'user' => 'staff',
                'rules' => [
                    [
                        'actions' => ['index', 'view', 'create', 'update', 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();

        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $dataProvider->pagination->pageSize = 10;

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     *
     * @param int $id
     *
     * @throws NotFoundHttpException if the model cannot be found
     *
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     *
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     *
     * @param int $id
     *
     * @throws NotFoundHttpException if the model cannot be found
     *
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     *
     * @param int $id
     *
     * @throws NotFoundHttpException if the model cannot be found
     *
     * @return mixed
     */
    public function actionDelete($id)
    {
        $user = $this->findModel($id);

        if (count($user->loans)) {
            Yii::$app->getSession()->setFlash('message', "Delete {$user->name}'s loans first.");

            return $this->redirect(['index']);
        }

        $user->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     *
     * @param int $id
     *
     * @throws NotFoundHttpException if the model cannot be found
     *
     * @return User the loaded model
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/user/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

// @var $this yii\web\View
// @var $model app\models\User
// @var $form yii\widgets\ActiveForm
?>

<div class="user-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'first_name')->textInput() ?>

    <?= $form->field($model, 'last_name')->textInput() ?>

    <?= $form->field($model, 'email')->input('email') ?>

    <?= $form->field($model, 'personal_code')->input('number') ?>

    <?= $form->field($model, 'phone')->input('tel') ?>

    <?= $form->field($model, 'active')->checkbox() ?>

    <?= $form->field($model, 'dead')->checkbox() ?>

    <?= $form->field($model, 'lang')->dropDownList(['est' => 'Estonian', 'en' => 'English']) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

// @var $this yii\web\View
// @var $model app\models\UserSearch
// @var $form yii\widgets\ActiveForm
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'first_name') ?>

    <?= $form->field($model, 'last_name') ?>

    <?= $form->field($model, 'email') ?>

    <?= $form->field($model, 'personal_code') ?>

    <?php // echo $form->field($model, 'phone')?>

    <?php // echo $form->field($model, 'active')->checkbox()?>

    <?php // echo $form->field($model, 'dead')->checkbox()?>

    <?php // echo $form->field($model, 'lang')?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user/create.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

// @var $this yii\web\View
// @var $model app\models\User
$this->title = 'Users / Register';
?>
<div class="user-create">

    <div class="row">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/site/index">Home</a></li>
                <li class="breadcrumb-item"><a href="/user/index">Users</a></li>
                <li class="breadcrumb-item active" aria-current="page">Register</li>
            </ol>
        </nav>
    </div>

    <div class="row">
        <?php if (yii::$app->session->hasFlash('message')): ?>
            <div class="alert alert-info alert-dismissible">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <?php echo yii::$app->session->getFlash('message'); ?>
            </div>
        <?php endif ?>
    </div>

    <div class="row" style="background-color: #f5f5f5; padding-top: 20px; padding-bottom: 5px; margin-bottom: 20px; border-radius: 5px;">

        <?php $form = ActiveForm::begin([
            'action' => ['create'],
            'method' => 'post',
        ]); ?>

        <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">

            <?= $form->field($model, 'first_name')->textInput() ?>

            <?= $form->field($model, 'last_name')->textInput() ?>

            <?= $form->field($model, 'email')->input('email') ?>

            <?= $form->field($model, 'personal_code')->input('number') ?>

        </div>

        <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">

            <?= $form->field($model, 'phone')->input('tel') ?>

            <?= $form->field($model, 'active')->checkbox() ?>

            <?= $form->field($model, 'dead')->checkbox() ?>

            <?= $form->field($model, 'lang')->dropDownList(['est' => 'Estonian', 'en' => 'English']) ?>

            <div class="form-group ">
                <?= Html::submitButton('Save', ['class' => 'btn btn-block btn-primary']) ?>
            </div>

        </div>

        <?php ActiveForm::end(); ?>

    </div>

    <?php // $this->render('_form', ['model' => $model])?>

</div>

views/user/index.php
<?php

use yii\grid\GridView;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

// @var $this yii\web\View
// @var $searchModel app\models\UserSearch
// @var $dataProvider yii\data\ActiveDataProvider

$this->title = 'Users';
?>
<div class="user-index">

    <div class="row">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/site/index">Home</a></li>
                <li class="breadcrumb-item active" aria-current="page">Users</li>
            </ol>
        </nav>
    </div>

    <div class="row">
        <?php if (yii::$app->session->hasFlash('message')): ?>
            <div class="alert alert-info alert-dismissible">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <?php echo yii::$app->session->getFlash('message'); ?>
            </div>
        <?php endif ?>
    </div>

    <div class="row" style="background-color: #f5f5f5; padding-top: 20px; padding-bottom: 5px; margin-bottom: 20px; border-radius: 5px;">

        <?php $form = ActiveForm::begin([
            'action' => ['index'],
            'method' => 'get',
        ]); ?>

            <div class="col-lg-2 col-md-3 col-sm-4 col-xs-6">
                <?= $form->field($searchModel, 'name') ?>
            </div>

            <div class="col-lg-2 col-md-3 col-sm-4 col-xs-6">
                <?= $form->field($searchModel, 'email') ?>
            </div>

            <div class="col-lg-2 col-md-3 col-sm-4 col-xs-6">
                <?= $form->field($searchModel, 'personal_code')->textInput(['type' => 'number']) ?>
            </div>

            <div class="col-lg-2 col-md-3 col-sm-4 col-xs-6">
                <?= $form->field($searchModel, 'phone')->textInput(['type' => 'number']) ?>
            </div>

            <div class="form-group col-lg-2 col-md-3 col-sm-4 col-xs-6">
                <label class="control-label" for="">&nbsp;</label>
                <?= Html::submitButton('Search', ['class' => 'btn btn-block btn-primary']) ?>
            </div>

        <?php ActiveForm::end(); ?>

    </div>

    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                <?= Html::encode($this->title) ?>
                <div class="pull-right">
                    <a href="create" class="btn btn-default btn-xs">
                        <span class="glyphicon glyphicon-plus"></span> Register
                    </a>
                </div>
            </div>
            <div class="panel-body row">
                <?= GridView::widget([
                    'dataProvider' => $dataProvider,
                    'layout' => "<div class='col-xs-12'><div class='table-responsive'>{items}</div>\n{summary}\n<div class='text-center'>{pager}</div></div>",
                    'tableOptions' => [
                        'class' => 'table table-striped table-hover text-nowrap',
                    ],
                    'columns' => [
                        [
                            'attribute' => 'name',
                            'format' => 'raw',
                            'value' => function ($model) {
                                return Html::a($model->name, ['user/view', 'id' => $model->id]);
                            },
                        ],
                        [
                            'attribute' => 'email',
                            'format' => 'email',
                            'contentOptions' => ['class' => 'text-left'],
                            'headerOptions' => ['class' => 'text-left'],
                        ],
                        [
                            'attribute' => 'personal_code',
                            'contentOptions' => ['class' => 'text-right'],
                            'headerOptions' => ['class' => 'text-right'],
                        ],
                        [
                            'attribute' => 'phone',
                            'label' => 'Phone No.',
                            'contentOptions' => ['class' => 'text-right'],
                            'headerOptions' => ['class' => 'text-right'],
                        ],
                        [
                            'attribute' => 'active',
                            'format' => 'raw',
                            'contentOptions' => ['class' => 'text-center'],
                            'headerOptions' => ['class' => 'text-center'],
                            'value' => function ($user) {
                                return $user->active ?
                                    Html::label('Yes', 'status', ['class' => 'label label-sm label-success']) :
                                    Html::label('No', 'status', ['class' => 'label label-sm label-danger']);
                            },
                        ],
                        [
                            'attribute' => 'dead',
                            'format' => 'raw',
                            'contentOptions' => ['class' => 'text-center'],
                            'headerOptions' => ['class' => 'text-center'],
                            'value' => function ($user) {
                                return $user->dead ?
                                    Html::label('Yes', 'status', ['class' => 'label label-sm label-danger']) :
                                    Html::label('No', 'status', ['class' => 'label label-sm label-success']);
                            },
                        ],
                        [
                            'class' => 'yii\grid\ActionColumn',
                            'contentOptions' => ['class' => 'actions'],
                            'buttons' => [
                                'loans' => function ($url, $model, $key) {
                                    $query = http_build_query(['LoanSearch' => ['user_id' => $model->id]]);

                                    return Html::a(
                                        '<span class="glyphicon glyphicon-th-list" aria-hidden="true"></span> ',
                                        ["loan/index?{$query}"]
                                    );
                                },
                            ],
                            'template' => '{update} {loans}',
                        ],
                    ],
                ]); ?>
            </div>
        </div>
    </div>

</div>

views/user/update.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

// @var $this yii\web\View
// @var $model app\models\User

$this->title = "Users / {$model->name} / Update";
?>
<div class="user-update">

    <div class="row">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/site/index">Home</a></li>
                <li class="breadcrumb-item"><a href="/user/index">Users</a></li>
                <li class="breadcrumb-item"><?= Html::a($model->name, ['view', 'id' => $model->id]) ?></li>
                <li class="breadcrumb-item active" aria-current="page">Edit</li>
            </ol>
        </nav>
    </div>

    <div class="row">
        <?php if (yii::$app->session->hasFlash('message')): ?>
            <div class="alert alert-info alert-dismissible">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <?php echo yii::$app->session->getFlash('message'); ?>
            </div>
        <?php endif ?>
    </div>

    <div class="row" style="background-color: #f5f5f5; padding-top: 20px; padding-bottom: 5px; margin-bottom: 20px; border-radius: 5px;">

        <?php $form = ActiveForm::begin([
            'action' => ['update', 'id' => $model->id],
            'method' => 'post',
        ]); ?>

        <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">

            <?= $form->field($model, 'first_name')->textInput() ?>

            <?= $form->field($model, 'last_name')->textInput() ?>

            <?= $form->field($model, 'email')->input('email') ?>

            <?= $form->field($model, 'personal_code')->input('number') ?>

        </div>

        <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">

            <?= $form->field($model, 'phone')->input('tel') ?>

            <?= $form->field($model, 'active')->checkbox() ?>

            <?= $form->field($model, 'dead')->checkbox() ?>

            <?= $form->field($model, 'lang')->dropDownList(['est' => 'Estonian', 'en' => 'English']) ?>

            <div class="form-group ">
                <?= Html::submitButton('Save', ['class' => 'btn btn-block btn-primary']) ?>
            </div>

        </div>

        <?php ActiveForm::end(); ?>

    </div>

    <?php // $this->render('_form', ['model' => $model])?>

</div>

views/user/view.php
<?php

use yii\helpers\Html;

// @var $this yii\web\View
// @var $model app\models\User

$this->title = "Users / {$model->name}";
\yii\web\YiiAsset::register($this);
?>
<div class="user-view">

    <div class="row">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/site/index">Home</a></li>
                <li class="breadcrumb-item"><a href="/user/index">Users</a></li>
                <li class="breadcrumb-item active" aria-current="page"><?= $model->name ?></li>
            </ol>
        </nav>
    </div>

    <div class="row">
        <?php if (yii::$app->session->hasFlash('message')): ?>
            <div class="alert alert-info alert-dismissible">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <?php echo yii::$app->session->getFlash('message'); ?>
            </div>
        <?php endif ?>
    </div>

    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                <?= Html::encode($model->name) ?>
                <div class="pull-right">
                    <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-info btn-xs']) ?>
                    <?= Html::a('Delete', ['delete', 'id' => $model->id], [
                        'class' => 'btn btn-danger btn-xs',
                        'data' => [
                            'confirm' => "Are you sure you want to delete {$model->name}?",
                            'method' => 'post',
                        ],
                    ]) ?>
                </div>
            </div>

            <div class="panel-body">

                <div class="row vrow">
                    <label class="control-label vlabel col-lg-3 col-md-4 col-sm-5 col-xs-12">
                        Name
                    </label>
                    <label class="control-label vvalue col-lg-9 col-md-8 col-sm-7 col-xs-12">
                        <?= $model->name ?>
                    </label>
                </div>

                <div class="row vrow">
                    <label class="control-label vlabel col-lg-3 col-md-4 col-sm-5 col-xs-12">
                        Date of birth
                    </label>
                    <label class="control-label vvalue col-lg-9 col-md-8 col-sm-7 col-xs-12">
                        <?= "{$model->birthDate->format('D, jS M Y')} (Age: {$model->age})" ?>
                    </label>
                </div>

                <div class="row vrow">
                    <label class="control-label vlabel col-lg-3 col-md-4 col-sm-5 col-xs-12">
                        Email Address
                    </label>
                    <label class="control-label vvalue col-lg-9 col-md-8 col-sm-7 col-xs-12">
                        <?= Html::mailto($model->email) ?>
                    </label>
                </div>

                <div class="row vrow">
                    <label class="control-label vlabel col-lg-3 col-md-4 col-sm-5 col-xs-12">
                        Personal Code
                    </label>
                    <label class="control-label vvalue col-lg-9 col-md-8 col-sm-7 col-xs-12">
                        <?= $model->personal_code ?>
                    </label>
                </div>

                <div class="row vrow">
                    <label class="control-label vlabel col-lg-3 col-md-4 col-sm-5 col-xs-12">
                        Phone No.
                    </label>
                    <label class="control-label vvalue col-lg-9 col-md-8 col-sm-7 col-xs-12">
                        <?= $model->phone ?>
                    </label>
                </div>

                <div class="row vrow">
                    <label class="control-label vlabel col-lg-3 col-md-4 col-sm-5 col-xs-12">
                        Is Active?
                    </label>
                    <label class="control-label vvalue col-lg-9 col-md-8 col-sm-7 col-xs-12">
                        <?= $model->active ? 'Yes' : 'No' ?>
                    </label>
                </div>

                <div class="row vrow">
                    <label class="control-label vlabel col-lg-3 col-md-4 col-sm-5 col-xs-12">
                        Is Dead?
                    </label>
                    <label class="control-label vvalue col-lg-9 col-md-8 col-sm-7 col-xs-12">
                        <?= $model->dead ? 'Yes' : 'No' ?>
                    </label>
                </div>

                <div class="row vrow">
                    <label class="control-label vlabel col-lg-3 col-md-4 col-sm-5 col-xs-12">
                        Language
                    </label>
                    <label class="control-label vvalue col-lg-9 col-md-8 col-sm-7 col-xs-12">
                        <?= $model->lang ?>
                    </label>
                </div>

            </div>

        </div>
    </div>

</div>